baseURL = "http://example.org/"
languageCode = "en-us"
title = "Gnonpy"
theme = "mainroad"

paginate = "10" # Number of posts per page
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

markup = "markdown"
# pygmentsUseClasses = false
pygmentsStyle = "monokai"
pygmentsCodeFencesGuessSyntax = false
pygmentsCodeFences = true

[Author]
    name = "Denis Viviès"
    bio = "Young data scientist fascinated by Python, I like tinkering neural networks and dissecting datasets with a beer by my side."
    avatar = "img/avatar.jpg"

[Params]
    subtitle = "Data Science that works (sometimes)" # Subtitle of your site
    description = "Using Python to solve problems that could happen in your life." # Description of your site
    opengraph = false
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    # postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
     postSections = ["blog", "news"] # alternative that shows more than one section's pages
    # dateformat = "2006-01-02" # change the format of dates


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = false # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = false # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    social_linkedin = "denis-viviès-python"
    social_github = "Gnonpi"
    social_email = "legnonpi@gmail.com"
